version: '3.1'

services:
  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ${HOME}/appdata/mysql/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%

  adminer:
    image: adminer
    restart: always
    hostname: adminer
    container_name: adminer
    ports:
      - 13306:8080